apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: construction-app
type: Opaque
stringData:
  DB_DSN: "postgres://user:pass@postgres-service:5432/journal?sslmode=disable"
  JWT_SECRET: "super-secret-key"
  ADMIN_PASSWORD: "admin123"
  POSTGRES_PASSWORD: "pass"
