name: Go tests

on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  go-integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: journal
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Postgres Service
        run: |
          apt-get update && apt-get install -y postgresql-client
          PGPASSWORD=pass psql -h postgres -U user -d journal -c 'SELECT 1;'

      - name: Run customer tests
        env:
          TEST_DB_DSN: postgres://user:pass@postgres:5432/journal?sslmode=disable
        run: go test ./tests/customer/... -v